package io.retailplanet.backend.elasticsearch.impl.struct;

import org.jetbrains.annotations.NotNull;

/**
 * @author w.glanzer, 23.06.2019
 */
public interface IIndexStructProvider
{

  /**
   * Creates the name of the index, generated by the given indextype and clientid
   *
   * @param pClientID  ID of the client
   * @param pIndexType Type of the index
   * @return the (re)generated name
   */
  @NotNull
  String createIndexName(@NotNull String pClientID, @NotNull String pIndexType) throws IllegalArgumentException;

  /**
   * Returns the mapping definition for the given index type
   *
   * @param pIndexType Type of the index
   * @return the mapping
   */
  @NotNull
  String createMapping(@NotNull String pIndexType) throws IllegalArgumentException;

}
