openapi: 3.0.0
info:
  title: retailplanet.io API
  description: |
    This document describes the backend structure of the current retailplanet.io backend webservices.
    # Important
    Most of the APIs are not public and should not be uses by third party apps. <br/>
    For official retailplanet.io (Copyright by con.ceptive solutions e.K.) use only!
  version: v2
  x-logo:
    url: 'https://www.conceptive.io/static/logo/symbol_text/300.png'
    altText: con.ceptive solutions e.K. Logo

servers:
  - url: https://api.retailplanet.io
    description: Official retailplanet.io API server endpoint

tags:
  - name: business
    description: |
      The business API is the public endpoint for companies, to push their product information to. <br/>
      If you want to push products (same flow for markets), the common workflow looks something like this: <br/>
      <ul>
        <li>Init the connection and get a transfer token</li>
        <li>Put all products, paged</li>
        <li>Invalidate token</li>
      </ul>

x-tagGroups:
  - name: External
    tags:
      - business

paths:
  /businesss/token/generate:
    get:
      summary: Generate a new session token
      description: |
        Init a new "put data" workflow and retrieve a session token. <br/>
        If this method was called before, the previous token will be invalidated immediately.
      tags:
        - business
      parameters:
        - name: clientid
          in: query
          required: true
          description: specifies the client, which the products belong to.
          schema:
            type: string
        - name: token
          in: query
          required: true
          description: |
            The access token for the current client.
          schema:
            type: string
      responses:
        200:
          description: User has correct permissions and was able to retrieve a session token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_token:
                    type: string
                    description: the newly created session token
                    example: token
                  valid_until:
                    type: number
                    description: specifies the timestamp (UTC) how long this token will be valid.
                    example: 2019-06-22T19:04:00.763Z
        500:
          description: Something went wrong during workflow

  /business/product:
    put:
      summary: Put Products
      description: Add new products to the clients storage
      tags:
        - business
      parameters:
        - name: session_token
          in: query
          required: true
          description: The current (valid) session token of a specific client
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minLength: 1
              maxLength: 100
              items:
                type: object
                description: a single result item
                properties:
                  name:
                    type: string
                    required: true
                    description: displayable name for the current result item
                  id:
                    type: string
                    required: true
                    description: unique id of the product
                  category:
                    type: string
                    description: category as plain text
                  url:
                    type: string
                    required: true
                    description: url pointing to a product page, where the client will be redirected to
                  price:
                    type: number
                    default: 0
                    description: current price
                  previews:
                    type: array
                    items:
                      type: string
                      description: url pointing to a picture
                  additionalInfos:
                    type: object
                    description: contains all additional informations about this product
                  availability:
                    type: object
                    description: contains information about the availability status in single retail stores
                    properties:
                      MARKET_ID:
                        description: Replace this key with the ID of the market, this availability information belongs to
                        properties:
                          type:
                            type: string
                            enum: [AVAILABLE, ORDERABLE, NOT_AVAILABLE]
                            description: this object provides information about the products availability status
                          quantity:
                            type: integer
                            description: how much pieces are available in the parent market currently
      responses:
        200:
          description: Products successfully added to session store
        415:
          description: Only application/json is allowed as content type

  /business/market:
    put:
      summary: Put Markets
      description: Add new markets to the clients storage
      tags:
        - business
      parameters:
        - name: session_token
          in: query
          required: true
          description: The current (valid) session token of a specific client
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minLength: 1
              maxLength: 100
              items:
                type: object
                properties:
                  name:
                    description: Displayable name of the market
                    type: string
                  id:
                    description: Unique ID
                    required: true
                    type: string
                  lat:
                    description: Latitude of the current market location
                    type: number
                  lng:
                    description: Longitude of the current market location
                    type: number
                  address:
                    description: Displayable address for the client. \n are used for linebreaks
                    type: string
      responses:
        200:
          description: Markets successfully added to session store
        404:
          description: Something went wrong during workflow

  /business/token/{token}:
    delete:
      summary: Invalidate a session token
      tags:
        - business
      parameters:
        - name: token
          in: path
          required: true
          description: token that should be invalidated
          schema:
            type: string
      responses:
        400:
          description: Missing token in path
        200:
          description: Token was marked for removal