openapi: 3.0.0
info:
  title: retailplanet.io API
  description: |
    This document describes the backend structure of the current retailplanet.io backend webservices.
    # Important
    Most of the APIs are not public and should not be uses by third party apps. <br/>
    For official retailplanet.io (Copyright by con.ceptive solutions e.K.) use only!
  version: v2
  x-logo:
    url: 'https://www.conceptive.io/static/logo/symbol_text/300.png'
    altText: con.ceptive solutions e.K. Logo

servers:
  - url: https://api.retailplanet.io
    description: Official retailplanet.io API server endpoint

tags:
  - name: search
  - name: business
    description: |
      The business API is the public endpoint for companies, to push their product information to. <br/>
      If you want to push products (same flow for markets), the common workflow looks something like this: <br/>
      <ul>
        <li>Init the connection and get a transfer token</li>
        <li>Put all products, paged</li>
        <li>Invalidate token</li>
      </ul>

x-tagGroups:
  - name: Internal
    tags:
      - search
  - name: External
    tags:
      - business

paths:
  /businesss/token/generate:
    get:
      summary: Generate a new session token
      description: |
        Init a new "put data" workflow and retrieve a session token. <br/>
        If this method was called before, the previous token will be invalidated immediately.
      tags:
        - business
      parameters:
        - name: clientid
          in: query
          required: true
          description: specifies the client, which the products belong to.
          schema:
            type: string
        - name: token
          in: query
          required: true
          description: |
            The access token for the current client.
          schema:
            type: string
      responses:
        200:
          description: User has correct permissions and was able to retrieve a session token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_token:
                    type: string
                    description: the newly created session token
                    example: token
                  valid_until:
                    type: number
                    description: specifies the timestamp (UTC) how long this token will be valid.
                    example: 2019-06-22T19:04:00.763Z
        500:
          description: Something went wrong during workflow

  /business/product:
    put:
      summary: Put Products
      description: Add new products to the clients storage
      tags:
        - business
      parameters:
        - name: session_token
          in: query
          required: true
          description: The current (valid) session token of a specific client
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minLength: 1
              maxLength: 100
              items:
                type: object
                description: a single result item
                properties:
                  name:
                    type: string
                    required: true
                    description: displayable name for the current result item
                  id:
                    type: string
                    required: true
                    description: unique id of the product
                  category:
                    type: string
                    description: category as plain text
                  url:
                    type: string
                    required: true
                    description: url pointing to a product page, where the client will be redirected to
                  price:
                    type: number
                    default: 0
                    description: current price
                  previews:
                    type: array
                    items:
                      type: string
                      description: url pointing to a picture
                  additionalInfos:
                    type: object
                    description: contains all additional informations about this product
                  availability:
                    type: object
                    description: contains information about the availability status in single retail stores
                    properties:
                      MARKET_ID:
                        description: Replace this key with the ID of the market, this availability information belongs to
                        properties:
                          type:
                            type: string
                            enum: [AVAILABLE, ORDERABLE, NOT_AVAILABLE]
                            description: this object provides information about the products availability status
                          quantity:
                            type: integer
                            description: how much pieces are available in the parent market currently
      responses:
        200:
          description: Products successfully added to session store
        415:
          description: Only application/json is allowed as content type

  /business/market:
    put:
      summary: Put Markets
      description: Add new markets to the clients storage
      tags:
        - business
      parameters:
        - name: session_token
          in: query
          required: true
          description: The current (valid) session token of a specific client
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minLength: 1
              maxLength: 100
              items:
                type: object
                properties:
                  name:
                    description: Displayable name of the market
                    type: string
                  id:
                    description: Unique ID
                    required: true
                    type: string
                  lat:
                    description: Latitude of the current market location
                    type: number
                  lng:
                    description: Longitude of the current market location
                    type: number
                  address:
                    description: Displayable address for the client. \n are used for linebreaks
                    type: string
      responses:
        200:
          description: Markets successfully added to session store
        404:
          description: Something went wrong during workflow

  /business/token/{token}:
    delete:
      summary: Invalidate a session token
      tags:
        - business
      parameters:
        - name: token
          in: path
          required: true
          description: token that should be invalidated
          schema:
            type: string
      responses:
        400:
          description: Missing token in path
        200:
          description: Token was marked for removal

  /search:
    get:
      summary: Product Search
      description: Executes a product search
      tags:
        - search
      parameters:
        - name: query
          in: query
          required: true
          description: query to search for
          schema:
            type: string
        - name: sort
          in: query
          required: false
          description: adds sorting to the results
          schema:
            type: string
            enum: [RELEVANCE_ASC, RELEVANCE_DESC, PRICE_ASC, PRICE_DESC]
            default: RELEVANCE_DESC
        - name: offset
          in: query
          required: false
          description: the current search offset as element count, not page count
          schema:
            type: number
        - name: length
          in: query
          required: false
          description: page size
          schema:
            type: number
            minimum: 0
            maximum: 100
        - name: filter
          in: query
          required: false
          description: all filters that should be applied on the given search request
          schema:
            type: object
            description: all filters, which describe a predicate that must match.<br/>Key = Name,<br/>Value = Array of information
            example:
              geo: [99, 99, 100]
      responses:
        500:
          description: something went wrong during search
        204:
          description: search successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  offset:
                    type: number
                    description: offset range given in search query
                  length:
                    type: number
                    description: length / size of this result page
                  maxSize:
                    type: number
                    description: maximum count of all results of this query
                  filters:
                    type: object
                    description: an object containing all possible filters on the client side with additional informations
                    properties:
                      price:
                        type: array
                        example:
                          - 7.99
                          - 100
                        items:
                          type: number
                        minItems: 2
                        maxItems: 2
                        description: contains two numbers, that specify the price range for the price filter. The first item specifies the lowest, the second item the highest price of the current resultset.
                  elements:
                    type: array
                    description: contains the current page of the resultset
                    items:
                      type: object
                      description: a single result item
                      properties:
                        name:
                          type: string
                          description: displayable name for the current result item
                        id:
                          type: string
                          description: id of the product
                        category:
                          type: string
                          description: product category
                        url:
                          type: string
                          description: url for this product, to redirect all external requests
                        price:
                          type: number
                          description: current price for the current result item
                        availability:
                          type: object
                          description: the markets object gives information about the availability of this product. It contains only these markets, where the products were found and the filters matched.
                          properties:
                            MARKETID:
                              type: object
                              description: this object describes a single retail store
                              properties:
                                type:
                                  type: string
                                  enum: [AVAILABLE, ORDERABLE, NOT_AVAILABLE]
                                  description: this object provides information about the products availability status in the parent market
                                quantity:
                                  type: integer
                                  description: how much pieces are available in the parent market currently
                        previews:
                          type: array
                          items:
                            type: string
                            description: URL pointing to a picture
                        additionalInfos:
                          type: object
                          description: contains all additional informations about this product