version: '3.3'

services:
  # =================
  # ==== STORAGE ====
  # =================

  # Elasticsearch
  search1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - cluster.name=retailplanet
      - node.name=search1
      - cluster.initial_master_nodes=search1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    volumes:
      - ./.elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # MongoDB
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.mongodb:/data/db

  # =======================
  # ==== DOCUMENTATION ====
  # =======================

  docs:
    image: redocly/redoc
    ports:
      - 9500:80
    volumes:
      - ./docs/public:/usr/share/nginx/html/public
    environment:
      - SPEC_URL=public/v1/endpoints.yml


  # ======================
  # ==== API Services ====
  # ======================

  # searchAPI-Service
  search:
    image: images.conceptive.io/retailplanet.backend.search.native:latest
    ports:
      - 8880:8080

  # BusinessAPI-Service
  businessapi:
    image: images.conceptive.io/retailplanet.backend.businessapi.native:latest
    ports:
      - 8881:8080

  # UserAuth-Service
  userauth:
    image: images.conceptive.io/retailplanet.backend.userauth.native:latest
    ports:
      - 8882:8080

  # ===========================
  # ==== Internal Services ====
  # ===========================

  # BusinessToken-Service
  businesstoken:
    image: images.conceptive.io/retailplanet.backend.businesstoken:latest # no native image, because H2 can not be embedded
    volumes:
      - ./.h2:/data/h2
    environment:
      H2_DATA: /data/h2/businesstoken

  # Elasticsearch-Service
  elasticsearch:
    image: images.conceptive.io/retailplanet.backend.elasticsearch.native:latest
    links:
      - search1
    environment:
      ELASTICSEARCH_SERVERS: search1:9200

  # Markets-Service
  markets:
    image: images.conceptive.io/retailplanet.backend.markets.native:latest

  # Products-Service
  products:
    image: images.conceptive.io/retailplanet.backend.products.native:latest

  # Metrics-Service
  metrics:
    image: images.conceptive.io/retailplanet.backend.metrics.native:latest
