version: '3.3'

services:

  # Zookeeper to manage kafka instances
  kafka_zookeeper:
    image: debezium/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./.kafka/zookeeper:/zookeeper/data
      - ./.kafka/zookeeper_conf:/zookeeper/conf

  # Kafka instance
  kafka:
    image: debezium/kafka:latest
    restart: always
    links:
      - kafka_zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./.kafka/kafka:/kafka/data
    environment:
      ZOOKEEPER_CONNECT: "kafka_zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT
      LISTENERS: "LOCAL://0.0.0.0:9092"
      ADVERTISED_LISTENERS: "LOCAL://kafka:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL

  # REST Documentation
  docs:
    image: redocly/redoc
    ports:
      - 9500:80
    volumes:
      - ./docs/public:/usr/share/nginx/html/public
    environment:
      - SPEC_URL=public/v1/endpoints.yml

  # Elasticsearch
  search1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - cluster.name=retailplanet
      - node.name=search1
      - cluster.initial_master_nodes=search1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    volumes:
      - ./.elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # BusinessAPI-Service
  businessapi:
    image: images.conceptive.io/retailplanet.backend.businessapi.native:latest
    links:
      - kafka
    ports:
      - 8888:8080
    environment:
      KAFKA_SERVERS: kafka:9092

  # BusinessToken-Service
  businesstoken:
    image: images.conceptive.io/retailplanet.backend.businesstoken:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092

  # Elasticsearch-Service
  elasticsearch:
    image: images.conceptive.io/retailplanet.backend.elasticsearch.native:latest
    links:
      - kafka
      - search1
    environment:
      KAFKA_SERVERS: kafka:9092
      ELASTICSEARCH_SERVERS: search1:9200

  # Markets-Service
  markets:
    image: images.conceptive.io/retailplanet.backend.markets.native:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092

  # Products-Service
  products:
    image: images.conceptive.io/retailplanet.backend.products.native:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092

  # UserAuth-Service
  userauth:
    image: images.conceptive.io/retailplanet.backend.userauth.native:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092