version: '3.3'

services:

  datadog:
    image: datadog/agent:latest
    restart: always
    environment:
      DD_API_KEY: 37c15f3762f1b01c79516bbdcc16ee15
      DD_TAGS: localhost
      DD_APM_ENABLED: "false"
      DD_LOGS_ENABLED: "true"
      DD_PROCESS_AGENT_ENABLED: "false"
      DD_AC_INCLUDE: "retailplanetio-backend-.*"
      DD_AC_EXCLUDE: ".*datadog.*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  # Zookeeper to manage kafka instances
  kafka_zookeeper:
    image: debezium/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./.kafka/zookeeper:/zookeeper/data
      - ./.kafka/zookeeper_conf:/zookeeper/conf

  # Kafka instance
  kafka:
    image: debezium/kafka:latest
    restart: always
    links:
      - kafka_zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./.kafka/kafka:/kafka/data
    environment:
      ZOOKEEPER_CONNECT: "kafka_zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT
      LISTENERS: "LOCAL://0.0.0.0:9092"
      ADVERTISED_LISTENERS: "LOCAL://kafka:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL

  # REST Documentation
  docs:
    image: redocly/redoc
    ports:
      - 9500:80
    volumes:
      - ./docs/public:/usr/share/nginx/html/public
    environment:
      - SPEC_URL=public/v1/endpoints.yml

  # Elasticsearch
  search1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - cluster.name=retailplanet
      - node.name=search1
      - cluster.initial_master_nodes=search1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    volumes:
      - ./.elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # BusinessAPI-Service
  businessapi:
    image: images.conceptive.io/retailplanet.backend.businessapi.native:latest
    links:
      - kafka
    ports:
      - 8888:8080
    environment:
      KAFKA_SERVERS: kafka:9092

  # BusinessToken-Service
  businesstoken:
    image: images.conceptive.io/retailplanet.backend.businesstoken:latest # no native image, because H2 can not be embedded
    links:
      - kafka
    volumes:
      - ./.h2:/data/h2
    environment:
      KAFKA_SERVERS: kafka:9092
      H2_DATA: /data/h2/businesstoken

  # Elasticsearch-Service
  elasticsearch:
    image: images.conceptive.io/retailplanet.backend.elasticsearch.native:latest
    links:
      - kafka
      - search1
    environment:
      KAFKA_SERVERS: kafka:9092
      ELASTICSEARCH_SERVERS: search1:9200

  # Markets-Service
  markets:
    image: images.conceptive.io/retailplanet.backend.markets.native:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092

  # Products-Service
  products:
    image: images.conceptive.io/retailplanet.backend.products.native:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092

  # UserAuth-Service
  userauth:
    image: images.conceptive.io/retailplanet.backend.userauth.native:latest
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092