version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - run: mvn -s .circleci.settings.xml dependency:get -Dartifact=io.retailplanet.backend:backend-parent:2.0-SNAPSHOT -DremoteRepositories=default::default::https://nexus.conceptive.io/repository/maven-public
      - checkout
      - run: mvn clean install
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo/target

  deploy_docker:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build application Docker image
          command: |
            cd /home/circleci/repo/target
            docker build -t images.conceptive.io/retailplanet.backend.businesstoken:${CIRCLE_BRANCH} .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS ${DOCKER_REGISTRY}
            docker push "${DOCKER_REGISTRY}/retailplanet.backend.businesstoken:${CIRCLE_BRANCH}"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_docker:
          requires:
            - build