version: '3.3'

services:
  db_local:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: businesstoken